const seedData = {
  users: [
    {
      name: 'Admin User',
      email: 'admin@hirehub.com',
      password: 'password123',
      role: 'admin',
      avatar: { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300' },
    },
    {
      name: 'Priya Sharma',
      email: 'recruiter@techcorp.com',
      password: 'password123',
      role: 'recruiter',
      avatar: { url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300' },
    },
    {
      name: 'Rajesh Verma',
      email: 'recruiter@innotech.com',
      password: 'password123',
      role: 'recruiter',
      avatar: { url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=300' },
    },
    {
      name: 'Aarav Patel',
      email: 'aarav@candidate.com',
      password: 'password123',
      role: 'candidate',
      avatar: { url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=300' },
    },
    {
      name: 'Ananya Gupta',
      email: 'ananya@candidate.com',
      password: 'password123',
      role: 'candidate',
      avatar: { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300' },
    },
  ],

  companies: [
    {
      name: 'TechCorp India',
      description: 'TechCorp India is a premier technology innovation hub in Electronic City, Bengaluru, specializing in cloud platforms, enterprise AI solutions, and scalable web apps.',
      industry: 'Information Technology',
      companySize: '501-1000',
      website: 'https://techcorp-india.example.com',
      location: 'Bengaluru, Karnataka',
      foundedYear: 2018,
      logo: { url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=300' },
    },
    {
      name: 'InnoTech Labs',
      description: 'InnoTech Labs designs cloud-native applications, web products, and mobile systems for fast-growing Indian tech startups and global brands.',
      industry: 'Software Development',
      companySize: '51-200',
      website: 'https://innotech-labs.example.com',
      location: 'Mumbai, Maharashtra',
      foundedYear: 2020,
      logo: { url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=300' },
    },
    {
      name: 'FinPulse Systems',
      description: 'FinPulse Systems drives fintech innovations in HITEC City, Hyderabad, engineering UPI payment gateways, algorithmic trading engines, and secure banking portals.',
      industry: 'Financial Technology',
      companySize: '201-500',
      website: 'https://finpulse.example.com',
      location: 'Hyderabad, Telangana',
      foundedYear: 2016,
      logo: { url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=300' },
    },
  ],

  jobs: [
    {
      title: 'Senior Full Stack Engineer (MERN)',
      description: 'We are seeking an experienced Full Stack Software Engineer to build scalable microservices and intuitive React UI dashboards for our cloud management console.',
      responsibilities: [
        'Design and implement high-performance RESTful APIs using Node.js and Express.',
        'Develop responsive, accessible React frontend components with Tailwind CSS.',
        'Optimize MongoDB queries and index schemas for high throughput.',
        'Collaborate with product managers and DevOps teams in an agile environment.',
      ],
      requirements: [
        '4+ years of hands-on experience software engineering with Node.js and React.',
        'Strong expertise in JavaScript, Express, MongoDB, and Redux/Context API.',
        'Experience with Docker, AWS/GCP CI/CD pipelines, and Jest testing framework.',
        'Excellent problem-solving skills and passion for clean architecture.',
      ],
      skills: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind CSS', 'TypeScript', 'Docker'],
      location: 'Bengaluru, Karnataka',
      workMode: 'Hybrid',
      jobType: 'Full-time',
      experienceLevel: 'Senior',
      salaryMin: 1500000,
      salaryMax: 2400000,
      salaryCurrency: 'INR',
    },
    {
      title: 'Frontend React Developer',
      description: 'Join our creative product team in Powai, Mumbai, to craft high-impact web apps, interactive visualizations, and design systems for enterprise software.',
      responsibilities: [
        'Convert Figma wireframes into pixel-perfect React components.',
        'Maintain dynamic state using modern React hooks and state management tools.',
        'Implement smooth micro-animations and accessibility standards.',
      ],
      requirements: [
        '3+ years building modern single-page applications in React.',
        'Proficiency with HTML5, CSS3, Tailwind CSS, and Vite/Webpack build tools.',
        'Familiarity with REST APIs and state management.',
      ],
      skills: ['React.js', 'Tailwind CSS', 'JavaScript', 'HTML5', 'Vite', 'Redux'],
      location: 'Mumbai, Maharashtra',
      workMode: 'Remote',
      jobType: 'Full-time',
      experienceLevel: 'Mid',
      salaryMin: 1000000,
      salaryMax: 1600000,
      salaryCurrency: 'INR',
    },
    {
      title: 'Backend Node.js API Architect',
      description: 'Drive the backend infrastructure for high-throughput financial systems handling millions of API transactions daily in Hyderabad.',
      responsibilities: [
        'Architect scalable microservices using Express, NestJS, and Redis caching.',
        'Ensure robust security, OAuth2 authentication, and data compliance.',
        'Write comprehensive unit and integration tests.',
      ],
      requirements: [
        '4+ years backend development experience with Node.js & MongoDB/PostgreSQL.',
        'Deep understanding of async I/O, event loops, and database indexing.',
        'Experience with AWS services (S3, Lambda, SQS).',
      ],
      skills: ['Node.js', 'Express.js', 'MongoDB', 'Redis', 'AWS', 'Security'],
      location: 'Hyderabad, Telangana',
      workMode: 'On-site',
      jobType: 'Full-time',
      experienceLevel: 'Senior',
      salaryMin: 1800000,
      salaryMax: 2800000,
      salaryCurrency: 'INR',
    },
    {
      title: 'UI/UX Product Designer',
      description: 'Craft intuitive customer journeys and responsive user interface prototypes for our fast-growing SaaS platform.',
      responsibilities: [
        'Conduct user research, persona creation, and usability interviews.',
        'Design interactive prototypes in Figma and create reusable design tokens.',
        'Partner closely with frontend engineers during UI implementation.',
      ],
      requirements: [
        '2+ years in UX/UI product design for Web and Mobile applications.',
        'Strong portfolio demonstrating end-to-end design methodology.',
      ],
      skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'],
      location: 'Gurugram, Haryana',
      workMode: 'Remote',
      jobType: 'Full-time',
      experienceLevel: 'Mid',
      salaryMin: 900000,
      salaryMax: 1400000,
      salaryCurrency: 'INR',
    },
  ],
};

module.exports = seedData;
